recurse()
add_sources(
    ent_geometry.cpp
    ent_geometry.h
    ent_geometry_events.h
    ent_geometry_outln.cpp
    ent_geometry_outln.h
    ent_geometry_serialize.cpp
    vertex_editor.h
    vertex_editor.cpp
)
