#include "event_defs.h"

ALLOC_EVENT_DEF(Apocalypse)
ALLOC_EVENT_DEF(LinkEntity)
ALLOC_EVENT_DEF(SpawnPolyhedron)
ALLOC_EVENT_DEF(SpawnMesh)
ALLOC_EVENT_DEF(DestroyEntity)
ALLOC_EVENT_DEF(Rebuild)
ALLOC_EVENT_DEF(SetVisible)
ALLOC_EVENT_DEF(SetName)
ALLOC_EVENT_DEF(SetPosition)
ALLOC_EVENT_DEF(SetScale)
ALLOC_EVENT_DEF(SetRotation)
ALLOC_EVENT_DEF(SetRenderFlags)
ALLOC_EVENT_DEF(SetPickable)
ALLOC_EVENT_DEF(SetNodeColor)
ALLOC_EVENT_DEF(SetEdgeColor)
ALLOC_EVENT_DEF(SetFaceColor)
ALLOC_EVENT_DEF(SetFaceVisibility)
ALLOC_EVENT_DEF(SetHullAlpha)
ALLOC_EVENT_DEF(SetEdgeBaseColor)
ALLOC_EVENT_DEF(SetEdgeRadius)
ALLOC_EVENT_DEF(SetEffect)
ALLOC_EVENT_DEF(Resize)
ALLOC_EVENT_DEF(Mouse)
ALLOC_EVENT_DEF(Key)
ALLOC_EVENT_DEF(RequestEntityInfo)
ALLOC_EVENT_DEF(EntityInfo)