recurse()
add_sources(
    box.cpp
    is_ray_box.cpp
    is_ray_plane.cpp
    is_ray_sphere.cpp
    line2.cpp
    line3.cpp
    math.cpp
    matrix3_mem.cpp
    matrix3_op.cpp
    matrix4_mem.cpp
    matrix4_op.cpp
    quaternion_mem.cpp
    vector2_mem.cpp
    vector2_op.cpp
    vector3_mem.cpp
    vector3_op.cpp
    view_frustrum.cpp
)
